repos:
    # Linting
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python3.8
    # flake8
-   repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-future-annotations==0.0.4',
      ]
    # Detect secrets
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json